#!/bin/bash

# Crear un directorio para instalar los paquetes y asegurarse de que el usuario tiene permisos
mkdir -p /tmp/pip-packages

# Actualizar pip a la última versión
python -m pip install --upgrade pip

# Instalar las dependencias en /tmp/pip-packages en lugar de /.local
pip install --no-cache-dir --prefix=/tmp/pip-packages -r requirements.txt